# Generated by Django 5.1.4 on 2024-12-14 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streamplatform',
            options={'verbose_name': 'StreamPlatform', 'verbose_name_plural': 'StreamPlatforms'},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'verbose_name': 'WatchList', 'verbose_name_plural': 'WatchLists'},
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.streamplatform'),
        ),
    ]
