# Generated by Django 5.1.4 on 2024-12-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_watchlist_rating_watchlist_rating_number_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='rating_sum',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
