# Generated by Django 5.1.4 on 2024-12-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0005_alter_watchlist_rating_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='rating_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
